spring.application.name=payment-service

# Eureka Service Discovery (SD) URL
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

eureka.instance.hostname=localhost

# Change Server
server.port=8082