spring.application.name=account-service

eureka.instance.hostname=localhost

# Eureka Service Discovery (SD) URL
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

# Change Server
server.port=8081